export const FETCH_INVOICES_BEGIN = 'FETCH_INVOICES_BEGIN';
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_ERROR = 'FETCH_INVOICES_ERROR';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const FILTER_INVOICES = 'FILTER_INVOICES';